Allow to skip unpublished flows and modules, add max-items, use instance B cf prefix, allow blanks in dir

diff --git a/bin/connect_save b/bin/connect_save
--- a/bin/connect_save
+++ b/bin/connect_save
@@ -6,42 +6,77 @@
 #
 
 USAGE=$(cat <<EOD
-Usage: connect_save [-?f] [-G ignore_prefix] instance_alias [aws_profile] [contact_flow_prefix]
+Usage: connect_save [-?fs] [-G ignore_prefix] instance_alias [aws_profile] [contact_flow_prefix]
     Retrieve resources from an Amazon Connect instance into plain files
 
     instance_alias       Alias of the Connect instance (or path to the directory to save, with the alias being the basename)
     profile              AWS Profile to use
     contact_flow_prefix  Prefix of Contact Flows and Modules of interest (all others will be ignored)
     -f                   Force removal of existing instance_alias directory
-    -G ignore_prefix     Ignore hours, queues, routing profiles, flows or modules with name prefixed with ignore_prefix
+    -s                   Skip unpublished contact flow modules and contact flows with an error, instead of failing
+    -G ignore_prefix     Ignore hours, queues, routing profiles, flows or modules with names prefixed with ignore_prefix
     -?                   Help
 EOD
 )
 usage() { echo -e "$USAGE" >&2; exit 2; }
 
-error() { echo -e "Error: $1" >&2; exit 1; }
-
-fix_module_json() {
-    # A workaround for AWS CLI failed to create contact flow modules
-    # with Transitions Errors and Conditions in the EndFlowModuleExecution block.
-    module_json=$1
-    x=$(jq -r ".Actions[] | select(.Type == \"EndFlowModuleExecution\") | .Transitions" "$module_json")
-    if [ "$x" == "{}" ]; then
-        return
-    fi
-    ii=0
-    cat "$module_json" > $TEMPFILE
-    cat "$TEMPFILE" |
-    jq -r ".Actions | map(.Type == \"EndFlowModuleExecution\") | .[]" |
-    while read x; do
-        if [ "$x" == "true" ]; then
-            # Transitions Errors and Conditions found at Action[ii] - delete them
-            cat "$module_json" > $TEMPFILE2
-            jq "del(.Actions[$ii].Transitions.Errors, .Actions[$ii].Transitions.Conditions)" $TEMPFILE2 > "$module_json"
+error() {
+    if [ "$#" -ne 0 ]; then
+        if [[ ! "$1" =~ ^[[:digit:]]+$ ]]; then
+            # Not an AWS CLI error
+            cat <<EOD >&2
+Error: $*
+EOD
+        else
+            # An AWS CLI error
+            line_no=$1
+            cf=$2
+            manifest=$3
+            if [ -n "$cf" -a -n "$manifest" -a -n "$skip_cf_errors" ]; then
+                # TEMPCF reused and needs to be emptied afterwards
+                cat $manifest |
+                jq -r "select(.Name != \"$cf\")" > $TEMPCF
+                cat $TEMPCF > $manifest
+                echo "\"$cf\" skipped and removed from $manifest."
+                echo
+                # Return ok to allow the main process to continue without this CF
+                > $TEMPCF
+                return 0
+            else
+                cat <<EOD >&2
+Error at line ${line_no}. Recommended actions:
+1. Create all required prompts on the target instance
+2. Publish all in-scope contact flows and contact flow modules (or use -s to skip them)
+3. Install the latest AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
+EOD
+            fi
         fi
-        ii=$[ii+1]
-    done
+    fi
+    exit 1
 }
+
+# # A workaround for contact flow modules created before 1 Dec 2021.
+# fix_module_json() {
+#     # A workaround for AWS CLI failed to create contact flow modules
+#     # with Transitions Errors and Conditions in the EndFlowModuleExecution block.
+#     module_json=$1
+#     x=$(jq -r ".Actions[] | select(.Type == \"EndFlowModuleExecution\") | .Transitions" "$module_json")
+#     if [ "$x" == "{}" ]; then
+#         return
+#     fi
+#     ii=0
+#     cat "$module_json" > $TEMPFILE
+#     cat "$TEMPFILE" |
+#     jq -r ".Actions | map(.Type == \"EndFlowModuleExecution\") | .[]" |
+#     while read x; do
+#         if [ "$x" == "true" ]; then
+#             # Transitions Errors and Conditions found at Action[ii] - delete them
+#             cat "$module_json" > $TEMPFILE2
+#             jq "del(.Actions[$ii].Transitions.Errors, .Actions[$ii].Transitions.Conditions)" $TEMPFILE2 > "$module_json"
+#         fi
+#         ii=$[ii+1]
+#     done
+# }
 
 aws_connect() {
     local cmd=""
@@ -60,22 +95,25 @@ aws_connect() {
 
 TEMPFILE=$(mktemp)
 TEMPFILE2=${TEMPFILE}_2
+TEMPCF=${TEMPFILE}_cf
 TEMPERR=${TEMPFILE}_err
-trap 'rm -r -- $TEMPFILE $TEMPFILE2 $TEMPERR' EXIT
-touch $TEMPFILE $TEMPFILE2 $TEMPERR
+trap 'rm -r -- $TEMPFILE $TEMPFILE2 $TEMPCF $TEMPERR' EXIT
+touch $TEMPFILE $TEMPFILE2 $TEMPCF $TEMPERR
 
-warning_awscli="Please install the latest AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
+maxitems=999
 
 forced=
+skip_cf_errors=
 ignore_prefix=
 jq_prefix_filter=
 jq_prefix_filter_text=
-while getopts "?fG:" arg; do
+while getopts "?fsG:" arg; do
   case "$arg" in
     f)  forced=on;;
+    s)  skip_cf_errors=on;;
     G)  ignore_prefix=$OPTARG
         jq_prefix_filter=" | select(.Name | test(\"^($ignore_prefix)\") | not)"
-        jq_prefix_filter_text=" excluding those with name prefixed with \"$ignore_prefix\""
+        jq_prefix_filter_text=" excluding those with names prefixed with \"$ignore_prefix\""
         ;;
     *)  usage;;
   esac
@@ -89,23 +127,23 @@ profile_flag=${profile:+ --profile $profile}
 
 contact_flow_prefix=$3
 contact_flow_prefix_filter=${contact_flow_prefix:+" | select(.Name | test(\"^($contact_flow_prefix|Default ).*\"))"}
-contact_flow_prefix_text="${contact_flow_prefix:+ with name prefixed with \"$contact_flow_prefix\"}"
+contact_flow_prefix_text="${contact_flow_prefix:+ with names prefixed with \"$contact_flow_prefix\"}"
 
 if [ -z "$instance_alias_dir" ]; then
     usage
 fi
 
-if [ -d $instance_alias_dir ]; then
+if [ -d "$instance_alias_dir" ]; then
     if [ -n "$forced" ]; then
-        echo "Existing Alias directory forcefully removed: $instance_alias_dir"
+        echo "Existing Alias directory forcefully removed: \"$instance_alias_dir\""
         rm -fr "$instance_alias_dir"
     else
-        error "Alias directory already exists. Remove and try again (or use -f): $instance_alias_dir"
+        error "Alias directory already exists. Remove and try again (or use -f): \"$instance_alias_dir\""
     fi
 fi
 
 cat <<EOD
-Instance Alias: $instance_alias (in directory $instance_alias_dir)
+Instance Alias: $instance_alias (in directory "$instance_alias_dir")
 AWS Profile: ${profile:-${AWS_PROFILE:-(default)}}
 Contact Flow Prefix: $contact_flow_prefix
 EOD
@@ -114,32 +152,36 @@ if [ -n "$ignore_prefix" ]; then
     echo "Ignore components with prefix: $ignore_prefix"
 fi
 
+if [ -n "$skip_cf_errors" ]; then
+    echo "Skip unpublished contact flow modules and contact flows with an error."
+fi
+
 ############################################################
 #
 # Instance
 #
 
-mkdir -p $instance_alias_dir
+mkdir -p "$instance_alias_dir"
 aws_cli_log="${instance_alias_dir%/}.log"
 > "$aws_cli_log"
 
 # First aws cli; only mkdir if successful.
-aws_connect list-instances > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+aws_connect list-instances --max-items $maxitems > $TEMPFILE
+test $? -eq 0 || error $LINENO
 
 instance_id=$(cat $TEMPFILE |
 jq -r ".InstanceSummaryList[] | select(.InstanceAlias == \"$instance_alias\")" |
-tee $instance_alias_dir/instance.json |
+tee "$instance_alias_dir/instance.json" |
 jq -r ".Id")
 echo "Instance ID: $instance_id"
 
 test -n "$instance_id" || error "Instance $instance_alias does not exist"
 
-cat $instance_alias_dir/instance.json |
+cat "$instance_alias_dir/instance.json" |
 grep : |
-sed -e's/ *"/instance_/' -e's/": /=/' -e's/,$//' > $instance_alias_dir/instance.var
-echo "aws_Profile=\"$profile\"" >> $instance_alias_dir/instance.var
-echo "instance_contact_flow_prefix=\"$contact_flow_prefix\"" >> $instance_alias_dir/instance.var
+sed -e's/ *"/instance_/' -e's/": /=/' -e's/,$//' > "$instance_alias_dir/instance.var"
+echo "aws_Profile=\"$profile\"" >> "$instance_alias_dir/instance.var"
+echo "instance_contact_flow_prefix=\"$contact_flow_prefix\"" >> "$instance_alias_dir/instance.var"
 
 
 ############################################################
@@ -149,12 +191,13 @@ echo "instance_contact_flow_prefix=\"$contact_flow_prefix\"" >> $instance_alias_
 
 aws_connect list-prompts \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 jq -r ".PromptSummaryList |= sort_by(.Name) | .[][]" |
-tee $instance_alias_dir/prompts.json |
-echo -e "\n$(jq -s "length") prompts listed in $instance_alias_dir/prompts.json"
+tee "$instance_alias_dir/prompts.json" |
+echo -e "\n$(jq -s "length") prompts listed in \"$instance_alias_dir/prompts.json\""
 
 
 ############################################################
@@ -164,23 +207,24 @@ echo -e "\n$(jq -s "length") prompts listed in $instance_alias_dir/prompts.json"
 
 aws_connect list-hours-of-operations \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 # jq -r ".HoursOfOperationSummaryList |= sort_by(.Name) | .[][]" |
 jq -r ".HoursOfOperationSummaryList[]$jq_prefix_filter" |
 jq -s "sort_by(.Name) | .[]" |
-tee $instance_alias_dir/hours.json |
-echo -e "\n$(jq -s "length") hours of operations listed in $instance_alias_dir/hours.json$jq_prefix_filter_text"
+tee "$instance_alias_dir/hours.json" |
+echo -e "\n$(jq -s "length") hours of operations listed in \"$instance_alias_dir/hours.json\"$jq_prefix_filter_text"
 
-jq -r ".Id + \" \" + .Name" $instance_alias_dir/hours.json |
+jq -r ".Id + \" \" + .Name" "$instance_alias_dir/hours.json" |
 while read hour_id hour_name; do
     echo "Exporting hours of operation $hour_name"
     aws_connect describe-hours-of-operation \
         --instance-id $instance_id \
         --hours-of-operation-id $hour_id \
         > "$instance_alias_dir/hour_$hour_name.json"
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+    test $? -eq 0 || error $LINENO
 done
 test $? -eq 0 || error
 
@@ -192,22 +236,23 @@ test $? -eq 0 || error
 
 aws_connect list-queues \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 jq -r ".QueueSummaryList[] | select(.QueueType != \"AGENT\")$jq_prefix_filter" |
 jq -s "sort_by(.Name) | .[]" |
-tee $instance_alias_dir/queues.json |
-echo -e "\n$(jq -s "length") queues listed in $instance_alias_dir/queues.json$jq_prefix_filter_text"
+tee "$instance_alias_dir/queues.json" |
+echo -e "\n$(jq -s "length") queues listed in \"$instance_alias_dir/queues.json\"$jq_prefix_filter_text"
 
-jq -r ".Id + \" \" + .Name" $instance_alias_dir/queues.json |
+jq -r ".Id + \" \" + .Name" "$instance_alias_dir/queues.json" |
 while read queue_id queue_name; do
     echo "Exporting queue $queue_name"
     aws_connect describe-queue \
         --instance-id $instance_id \
         --queue-id $queue_id \
         > "$instance_alias_dir/queue_$queue_name.json"
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+    test $? -eq 0 || error $LINENO
 done
 test $? -eq 0 || error
 
@@ -219,27 +264,29 @@ test $? -eq 0 || error
 
 aws_connect list-routing-profiles \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 jq -r ".RoutingProfileSummaryList[]$jq_prefix_filter" |
 jq -s "sort_by(.Name) | .[]" |
-tee $instance_alias_dir/routings.json |
-echo -e "\n$(jq -s "length") routing profiles listed in $instance_alias_dir/routings.json$jq_prefix_filter_text"
+tee "$instance_alias_dir/routings.json" |
+echo -e "\n$(jq -s "length") routing profiles listed in \"$instance_alias_dir/routings.json\"$jq_prefix_filter_text"
 
-jq -r ".Id + \" \" + .Name" $instance_alias_dir/routings.json |
+jq -r ".Id + \" \" + .Name" "$instance_alias_dir/routings.json" |
 while read routing_id routing_name; do
     echo "Exporting routing profile $routing_name"
     aws_connect describe-routing-profile \
         --instance-id $instance_id \
         --routing-profile-id $routing_id \
         > "$instance_alias_dir/routing_$routing_name.json"
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+    test $? -eq 0 || error $LINENO
     aws_connect list-routing-profile-queues \
         --instance-id $instance_id \
         --routing-profile-id $routing_id \
+        --max-items $maxitems \
         > "$instance_alias_dir/routingQs_$routing_name.json"
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+    test $? -eq 0 || error $LINENO
 done
 test $? -eq 0 || error
 
@@ -251,13 +298,14 @@ test $? -eq 0 || error
 
 aws_connect list-contact-flow-modules \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 jq -r ".ContactFlowModulesSummaryList[]${contact_flow_prefix_filter}${jq_prefix_filter}" |
 jq -s "sort_by(.Name) | .[]" |
-tee $instance_alias_dir/modules.json |
-echo -e "\n$(jq -s "length") contact flow modules listed in $instance_alias_dir/modules.json$contact_flow_prefix_text$jq_prefix_filter_text"
+tee "$instance_alias_dir/modules.json" |
+echo -e "\n$(jq -s "length") contact flow modules listed in \"$instance_alias_dir/modules.json\"$contact_flow_prefix_text$jq_prefix_filter_text"
 
 
 ############################################################
@@ -265,16 +313,30 @@ echo -e "\n$(jq -s "length") contact flow modules listed in $instance_alias_dir/
 # Export Contact Flow Modules
 #
 
-jq -r ".Id + \" \" + .Name" $instance_alias_dir/modules.json |
+cat "$instance_alias_dir/modules.json" > $TEMPFILE
+jq -r ".Id + \" \" + .Name" $TEMPFILE |
 while read module_id module_name; do
     echo "Exporting contact flow module $module_name"
     aws_connect describe-contact-flow-module \
         --instance-id $instance_id \
-        --contact-flow-module-id $module_id > $TEMPFILE
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
-    cat $TEMPFILE |
-    jq -r '.ContactFlowModule.Content' > "$instance_alias_dir/module_$module_name.json"
-    fix_module_json "$instance_alias_dir/module_$module_name.json"
+        --contact-flow-module-id $module_id > $TEMPCF
+    test $? -eq 0 || error $LINENO "$module_name" "$instance_alias_dir/modules.json"
+    if [ -s $TEMPCF ]; then
+        # Status == "saved" is considered a failure,
+        # not to copy an unpublished contact flow module
+        cf_status=$(jq -r ".ContactFlowModule.Status" $TEMPCF)
+        if [ "$cf_status" != "published" ]; then
+            echo
+            echo "$module_name: Contact flow module not published"
+            # Let error decide if continue or not
+            error $LINENO "$module_name" "$instance_alias_dir/modules.json"
+        fi
+        if [ -s $TEMPCF ]; then
+            cat $TEMPCF |
+            jq -r '.ContactFlowModule.Content' > "$instance_alias_dir/module_$module_name.json"
+            # fix_module_json "$instance_alias_dir/module_$module_name.json"
+        fi
+    fi
 done
 test $? -eq 0 || error
 
@@ -286,13 +348,14 @@ test $? -eq 0 || error
 
 aws_connect list-contact-flows \
     --instance-id $instance_id \
+    --max-items $maxitems \
     > $TEMPFILE
-test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
+test $? -eq 0 || error $LINENO
 cat $TEMPFILE |
 jq -r ".ContactFlowSummaryList[]${contact_flow_prefix_filter}${jq_prefix_filter}" |
 jq -s "sort_by(.Name) | .[]" |
-tee $instance_alias_dir/flows.json |
-echo -e "\n$(jq -s "length") contact flows listed in $instance_alias_dir/flows.json$contact_flow_prefix_text$jq_prefix_filter_text"
+tee "$instance_alias_dir/flows.json" |
+echo -e "\n$(jq -s "length") contact flows listed in \"$instance_alias_dir/flows.json\"$contact_flow_prefix_text$jq_prefix_filter_text"
 
 
 ############################################################
@@ -300,15 +363,18 @@ echo -e "\n$(jq -s "length") contact flows listed in $instance_alias_dir/flows.j
 # Export Contact Flows
 #
 
-jq -r ".Id + \" \" + .Name" $instance_alias_dir/flows.json |
+cat "$instance_alias_dir/flows.json" > $TEMPFILE
+jq -r ".Id + \" \" + .Name" $TEMPFILE |
 while read flow_id flow_name; do
     echo "Exporting contact flow $flow_name"
     aws_connect describe-contact-flow \
         --instance-id $instance_id \
-        --contact-flow-id $flow_id > $TEMPFILE
-    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
-    cat $TEMPFILE |
-    jq -r '.ContactFlow.Content' > "$instance_alias_dir/flow_$flow_name.json"
+        --contact-flow-id $flow_id > $TEMPCF
+    test $? -eq 0 || error $LINENO "$flow_name" "$instance_alias_dir/flows.json"
+    if [ -s $TEMPCF ]; then
+        cat $TEMPCF |
+        jq -r '.ContactFlow.Content' > "$instance_alias_dir/flow_$flow_name.json"
+    fi
 done
 test $? -eq 0 || error
 
