Updated 6/20/22 Amazon Connect migration scripts - Development version

diff --git a/bin/connect_diff b/bin/connect_diff
--- a/bin/connect_diff
+++ b/bin/connect_diff
@@ -1,3 +1,4 @@
+
 #!/bin/bash
 
 ############################################################
@@ -6,8 +7,12 @@
 # Note: This script does not use AWS CLI but instead uses results from
 #   connect_save on instance A and B.
 #
+# Added support to use mapping file for Lambda and Lex
+# This is useful when Lambda function name in destination account is different then in source account
+# 
+#
 
-VERSION=1.1
+VERSION=1.2.2b
 SCRIPT_VERSION="$(basename $0) $VERSION"
 
 USAGE=$(cat <<EOD
@@ -33,10 +38,21 @@ EOD
 )
 usage() { echo -e "$USAGE" >&2; exit 2; }
 version() { echo -e "$SCRIPT_VERSION"; exit; }
+dos2unix() { tr -d '\r'; }
 
 error() { echo -e "Error: $1" >&2; exit 1; }
 
-hex_code() { printf '%s' "$1" | xxd -u -p -c1 | while read x; do printf "%%%s" "$x"; done }
+hex_cmd=
+if [ -x "$(command -v xxd)" ]; then
+  hex_cmd="xxd -u -p -c1"
+elif [ -x "$(command -v hexdump)" ]; then
+  hex_cmd="hexdump -v -e '/1 \"%02X\n\"'"
+elif [ -x "$(command -v od)" ]; then
+  hex_cmd="od -An -vtx1 | tr [:lower:] [:upper:] | for i in \$(cat); do echo \$i; done"
+fi
+test -z "$hex_cmd" && error "Cannot find any hex conversion commands. Please install one of these: xxd, hexdump, od"
+hex_code() { printf '%s' "$1" | eval "$hex_cmd" | while read x; do printf "%%%s" "$x"; done }
+# hex_code() { printf '%s' "$1" | xxd -u -p -c1 | while read x; do printf "%%%s" "$x"; done }
 
 path_encode()  {
     old_lc_collate=$LC_COLLATE
@@ -63,6 +79,76 @@ add_file() {
         echo "$file_suffix" >> $helper_file
     fi
 }
+
+###########################################################################################################
+## Evaluate what resources exist in source instance and what in destination, and create old and new helper files
+##
+eval_resources() {
+   restype="$1"
+   resource="$2"
+   resfile="$3"
+   rp_to_ignore="$4"
+   rpq="$5"
+   
+   jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a"/"$resfile" |
+   dos2unix |
+   while read resource_id_a resource_name_a; do
+      if [ "$resource_name_a" == "$rp_to_ignore" ]; then
+        continue
+      fi
+      resource_name_encoded_a=$(path_encode "$resource_name_a")
+##      resource_id_b=$(jq -r "select(.Name == \"$resource_name_a\") | .Id" "$instance_alias_dir_b"/"$resfile")
+##      resource_id_b=$(jq -r "select(.Name == \"${resource_name_a//\"/\\\"}\") | .Id" "$instance_alias_dir_b"/"$resfile")
+      resource_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b"/"$resfile" | jq -r "select(.Name == \"${resource_name_a//\"/%22}\") | .Id" | dos2unix)
+      if [ -z "$resource_id_b" ]; then
+	## Resource does not exist in destination - let's do case insensitive check to make sure with regex (^ and $ for exact match)
+	resource_id_b=$(jq -r -c "select(.Name | match(\"^$resource_name_a$\";\"i\")) |  .Id" "$instance_alias_dir_b"/"$resfile" | dos2unix)
+  	if [ -z "$resource_id_b" ]; then
+		## Resource does not exist in destination
+        	add_file "$instance_alias_dir_a" "${resource}${resource_name_encoded_a}.json" $helper_new
+		## If resource is routing profile then we need to also account for queues configuration in routing profile
+		if [ "$restype" = "RP" ]; then
+		   add_file "$instance_alias_dir_a" "${rpq}${resource_name_encoded_a}.json" $helper_new
+		fi
+        else
+		## Resource exists in destination but name in source and destination have some lower-upper case differences
+		## Get the destination resource name and rename it to same name as source instance name
+		resource_name_b=$(jq -r "select(.Id == \"$resource_id_b\") | .Name" "$instance_alias_dir_b"/"$resfile")
+	        resource_name_encoded_b=$(path_encode "$resource_name_b")
+		mv "$instance_alias_dir_b"/"${resource}${resource_name_encoded_b}.json" "$instance_alias_dir_b"/"${resource}${resource_name_encoded_a}.json"
+        	add_file "$instance_alias_dir_b" "${resource}${resource_name_encoded_a}.json" $helper_old
+		## If resource is routing profile then we need to also account for queues configuration in routing profile
+		if [ "$restype" = "Queues" ]; then
+		   ## if there is a case difference then set the name of queue quick connect same as source instance case
+		   mv "$instance_alias_dir_b"/"${rpq}${resource_name_encoded_b}.json" "$instance_alias_dir_b"/"${rpq}${resource_name_encoded_a}.json"
+		fi
+		if [ "$restype" = "RP" ]; then
+		   ## if there is a case difference then set the name of queue config in routing profile same as source instance case
+		   mv "$instance_alias_dir_b"/"${rpq}${resource_name_encoded_b}.json" "$instance_alias_dir_b"/"${rpq}${resource_name_encoded_a}.json"
+  		   add_file "$instance_alias_dir_b" "${rpq}${resource_name_encoded_a}.json" $helper_old
+		fi
+        	cat <<EOD >> $helper_sed
+# Add Ids in sed file for replacement
+s%$resource_id_a%$resource_id_b%g
+EOD
+       fi
+    else
+	## Resource exists in destination
+        add_file "$instance_alias_dir_b" "${resource}${resource_name_encoded_a}.json" $helper_old
+	## If resource is routing profile then we need to also account for queues configuration in routing profile
+	if [ "$restype" = "RP" ]; then
+	   add_file "$instance_alias_dir_b" "${rpq}${resource_name_encoded_a}.json" $helper_old
+	fi
+        cat <<EOD >> $helper_sed
+# Add Ids in sed file for replacement
+s%$resource_id_a%$resource_id_b%g
+EOD
+    fi
+   done
+   test $? -eq 0 || error
+##
+} ## End of eval_resources
+###########################################################################################################
 
 forced=
 ignore_improper_extended_ascii=
@@ -102,6 +188,10 @@ EOD
         exit 1
     fi
 fi
+TEMPFILE1=$(mktemp)
+TEMPFILE2="$TEMPFILE1"_2
+trap 'rm -r -- $TEMPFILE1 $TEMPFILE2' EXIT
+touch $TEMPFILE1 $TEMPFILE2
 
 instance_alias_dir_a=$1
 instance_alias_a=$(basename "$instance_alias_dir_a")
@@ -113,6 +203,18 @@ helper=$3
 # Backward compatibility - if they are set, ignore the arguments
 lambda_prefix_a=${lambda_prefix_a:-$4}
 lambda_prefix_b=${lambda_prefix_b:-$5}
+
+## Set directories
+homedir=`pwd`
+rscdir="${homedir}/resources"
+## There are two flow Exceptions file - if we have phone mapping configured then we won't skip flows with hard-coded outbound caller Id set
+## else we have to skip those flows. We will set which flow Execption file to use based phone mapping
+flowExceptions1="${rscdir}/flowExceptions"
+flowExceptions2="${rscdir}/flowExceptions_phone"
+
+## Added resource name mapping to be replaced from src to dest account
+## e.g. lambda src-function-name dest-function-name
+resource_map="${rscdir}/resourceMap"
 
 if [ -z "$instance_alias_a" -o -z "$instance_alias_b" -o -z "$helper" ]; then
     usage
@@ -174,6 +276,7 @@ instance_arn_a=$instance_Arn
 eval $(echo $instance_arn_a | (IFS=: read x x x r a x; echo "region_a=$r; aws_ac_a=$a"))
 region_a=$region_a
 aws_ac_a=$aws_ac_a
+aws_profile_a=$aws_Profile
 echo "instance_id_a=\"$instance_id_a\"" | tee -a $helper_var
 echo "instance_arn_a=\"$instance_arn_a\"" | tee -a $helper_var
 echo "region_a=\"$region_a\"" | tee -a $helper_var
@@ -188,6 +291,7 @@ instance_arn_b=$instance_Arn
 eval $(echo $instance_arn_b | (IFS=: read x x x r a x; echo "region_b=$r; aws_ac_b=$a"))
 region_b=$region_b
 aws_ac_b=$aws_ac_b
+aws_profile_b=$aws_Profile
 echo "instance_id_b=\"$instance_id_b\"" | tee -a $helper_var
 echo "instance_arn_b=\"$instance_arn_b\"" | tee -a $helper_var
 echo "region_b=\"$region_b\"" | tee -a $helper_var
@@ -213,10 +317,106 @@ s%$instance_id_a%$instance_id_b%g
 s%$connect_arn_prefix_a%$connect_arn_prefix_b%g
 EOD
 
+### Read resource mapping file and add the sed commands
+## By default we will use flowException file#1 that will skip migrating flows with hard-coded phone numbers
+## If we have phone mapping configured in resourceMap file then we will use flowException file#2
+echo "flowExceptions1" > $TEMPFILE1
+skipPhonemapping=0
+echo $skipPhonemapping > $TEMPFILE2
+if [ -e "$resource_map" ]; then
+   echo "Reading resource mapping to set up Lambda, Lex bots, and Phone numbers..."
+   cat $resource_map | 
+   while read res_type res_src res_dest; do
+    #### check if this is "lambda"
+	if [ "$res_type" = "lambda" ]; then
+		lambda_arn_prefix_a="arn:aws:lambda:$region_a:$aws_ac_a:function:$res_src"
+		lambda_arn_prefix_b="arn:aws:lambda:$region_b:$aws_ac_b:function:$res_dest"
+    		echo "s%$lambda_arn_prefix_a%$lambda_arn_prefix_b%g" >> $helper_sed
+	fi
+    #### End of "lambda"
+
+    #### check if this is "bot"
+	if [ "$res_type" = "bot" ]; then
+		## Check if this is bot type v2
+		bot_name=$res_src
+        cnt=`echo $bot_name | grep : | wc -l`
+        if [ "$cnt" == "1" ]; then
+            ## This is Lex V2 bot
+            botnameV2=`echo $bot_name | cut -f1 -d':'`
+            botaliasV2=`echo $bot_name | cut -f2 -d':'`
+			## Get bot-Id of this V2 bot
+			v2botid=`aws lexv2-models list-bots --profile $aws_profile_a | jq -r ".botSummaries[] | select(.botName == \"$botnameV2\") | { botId }" | jq -r ".botId"`
+			## now get alias-id using botid
+			v2aliasid=`aws lexv2-models list-bot-aliases --profile $aws_profile_a --bot-id $v2botid | jq -r ".botAliasSummaries[] | select(.botAliasName == \"$botaliasV2\") | { botAliasId }" | jq -r ".botAliasId"`
+			## Now create bot Alias arn
+			v2aliasarn_a=arn:aws:lex:$region_a:$aws_ac_a:bot-alias/$v2botid/$v2aliasid
+			bot_v2_a='"lexV2BotName":"'${botnameV2}'","lexV2BotAliasName":"'${botaliasV2}'"'
+
+			## now find arn of destination instance bot
+			bot_name=$res_dest
+            botnameV2=`echo $bot_name | cut -f1 -d':'`
+            botaliasV2=`echo $bot_name | cut -f2 -d':'`
+			## Get bot-Id of this V2 bot
+			v2botid=`aws lexv2-models list-bots --profile $aws_profile_b | jq -r ".botSummaries[] | select(.botName == \"$botnameV2\") | { botId }" | jq -r ".botId"`
+			## now get alias-id using botid
+			v2aliasid=`aws lexv2-models list-bot-aliases --profile $aws_profile_b --bot-id $v2botid | jq -r ".botAliasSummaries[] | select(.botAliasName == \"$botaliasV2\") | { botAliasId }" | jq -r ".botAliasId"`
+			## Now create bot Alias arn
+			v2aliasarn_b=arn:aws:lex:$region_b:$aws_ac_b:bot-alias/$v2botid/$v2aliasid
+			bot_v2_b='"lexV2BotName":"'${botnameV2}'","lexV2BotAliasName":"'${botaliasV2}'"'
+			echo "s%$bot_v2_a%$bot_v2_b%g" >> $helper_sed
+    		echo "s%$v2aliasarn_a%$v2aliasarn_b%g" >> $helper_sed
+		else
+			## This is v1 (Classic) bot
+			## Bot name and region replacement for v1 type of bot
+  	        bot_a='"LexBot":{"Name":"'${res_src}'","Region":"'${region_a}'"'
+           	bot_b='"LexBot":{"Name":"'${res_dest}'","Region":"'${region_b}'"'
+	 		echo "s%$bot_a%$bot_b%g" >> $helper_sed
+		fi
+       		echo "lex_$res_dest" >> $helper_new
+	fi
+    #### End of "bot"
+
+    #### check if this is "phonenumber"
+	if [ "$res_type" = "phonenumber" -a "$skipPhonemapping" -eq "0" ]; then
+        ## Let's retrieve phone number Id
+		phonenumber_a=`cat "$instance_alias_dir_a/phonenumbers.json" | jq -r "select(.PhoneNumber == \"$res_src\") | { Id }" | jq -r ".Id"`
+		phonenumber_b=`cat "$instance_alias_dir_b/phonenumbers.json" | jq -r "select(.PhoneNumber == \"$res_dest\") | { Id }" | jq -r ".Id"`
+        if [ "$phonenumber_a" != "" -a "$phonenumber_b" != "" ]; then
+            ##
+            echo "s%$phonenumber_a%$phonenumber_b%g" >> $helper_sed
+            echo "s%$res_src%$res_dest%g" >> $helper_sed
+            echo "flowExceptions2" > $TEMPFILE1
+        else
+            echo "flowExceptions1" > $TEMPFILE1
+            skipPhonemapping=1
+            echo $skipPhonemapping > $TEMPFILE2
+            error "Source phone number - $res_src, or destination phone number - $res_dest does not exist in respective instance, please check the number configured in resourceMap"
+        fi
+	fi
+    #### End of "phonenumber"
+   done
+fi
+
 lambda_arn_prefix_a="arn:aws:lambda:$region_a:$aws_ac_a:function:$lambda_prefix_a"
 lambda_arn_prefix_b="arn:aws:lambda:$region_b:$aws_ac_b:function:$lambda_prefix_b"
 if [ "$lambda_arn_prefix_a" != "$lambda_arn_prefix_b" ]; then
     echo "s%$lambda_arn_prefix_a%$lambda_arn_prefix_b%g" >> $helper_sed
+fi
+
+## Set the flowExceptions file name that will be used in "copy" script
+## If phone mapping was configured and we had an error then exit here
+skipPhonemapping=`cat $TEMPFILE2`
+if [ "$skipPhonemapping" = "1" ];then
+    exit 1
+fi
+
+flowExceptionToUse=`cat $TEMPFILE1`
+if [ "$flowExceptionToUse" = "flowExceptions1" ]; then
+    ## We use flowException file that will skip flows with hard-coded caller Id settings
+    echo "flowExceptions=\"$flowExceptions1\"" | tee -a $helper_var
+else
+    ## We use flowException file that will not skip flows with hard-coded caller Id settings as we are doing phone mapping
+    echo "flowExceptions=\"$flowExceptions2\"" | tee -a $helper_var
 fi
 
 echo
@@ -228,11 +428,11 @@ echo
 
 echo Checking Prompts ...
 jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/prompts.json" |
-tr -d '\r' |
+dos2unix |
 while read prompt_id_a prompt_name; do
     prompt_name_encoded=$(path_encode "$prompt_name")
     # prompt_id_b=$(jq -r "select(.Name == \"${prompt_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/prompts.json")
-    prompt_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/prompts.json" | jq -r "select(.Name == \"${prompt_name//\"/%22}\") | .Id")
+    prompt_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/prompts.json" | jq -r "select(.Name == \"${prompt_name//\"/%22}\") | .Id" | dos2unix)
     if [ -z "$prompt_id_b" ]; then
         echo "prompt_$prompt_name" >> $helper_new
     else
@@ -251,24 +451,11 @@ test $? -eq 0 || error
 # Hours of operations
 #
 
-echo Checking Hours of operations ...
-jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/hours.json" |
-tr -d '\r' |
-while read hour_id_a hour_name; do
-    hour_name_encoded=$(path_encode "$hour_name")
-    # hour_id_b=$(jq -r "select(.Name == \"${hour_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/hours.json")
-    hour_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/hours.json" | jq -r "select(.Name == \"${hour_name//\"/%22}\") | .Id")
-    if [ -z "$hour_id_b" ]; then
-        add_file "$instance_alias_dir_a" "hour_$hour_name_encoded.json" $helper_new
-    else
-        add_file "$instance_alias_dir_b" "hour_$hour_name_encoded.json" $helper_old
-        cat <<EOD >> $helper_sed
-# Hour of operation: $hour_name
-s%$hour_id_a%$hour_id_b%g
-EOD
-    fi
-done
-test $? -eq 0 || error
+echo Checking Hours of operation ...
+restype="Hours"
+resource="hour_"
+resfile="hours.json"
+eval_resources "$restype" "$resource" "$resfile" "none" "none"
 
 
 ############################################################
@@ -277,23 +464,11 @@ test $? -eq 0 || error
 #
 
 echo Checking Queues ...
-jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/queues.json" |
-tr -d '\r' |
-while read queue_id_a queue_name; do
-    queue_name_encoded=$(path_encode "$queue_name")
-    # queue_id_b=$(jq -r "select(.Name == \"${queue_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/queues.json")
-    queue_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/queues.json" | jq -r "select(.Name == \"${queue_name//\"/%22}\") | .Id")
-    if [ -z "$queue_id_b" ]; then
-        add_file "$instance_alias_dir_a" "queue_$queue_name_encoded.json" $helper_new
-    else
-        add_file "$instance_alias_dir_b" "queue_$queue_name_encoded.json" $helper_old
-        cat <<EOD >> $helper_sed
-# Queue: $queue_name
-s%$queue_id_a%$queue_id_b%g
-EOD
-    fi
-done
-test $? -eq 0 || error
+restype="Queues"
+resource="queue_"
+resfile="queues.json"
+queue_qc="queue_qc_"
+eval_resources "$restype" "$resource" "$resfile" "none" "$queue_qc"
 
 
 ############################################################
@@ -302,29 +477,11 @@ test $? -eq 0 || error
 #
 
 echo Checking Routing Profiles ...
-jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/routings.json" |
-tr -d '\r' |
-while read routing_id_a routing_name; do
-    if [ "$routing_name" == "$routing_profile_to_ignore" ]; then
-        continue
-    fi
-    routing_name_encoded=$(path_encode "$routing_name")
-    # routing_id_b=$(jq -r "select(.Name == \"${routing_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/routings.json")
-    routing_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/routings.json" | jq -r "select(.Name == \"${routing_name//\"/%22}\") | .Id")
-    if [ -z "$routing_id_b" ]; then
-        add_file "$instance_alias_dir_a" "routing_$routing_name_encoded.json" $helper_new
-        add_file "$instance_alias_dir_a" "routingQs_$routing_name_encoded.json" $helper_new
-    else
-        add_file "$instance_alias_dir_b" "routing_$routing_name_encoded.json" $helper_old
-        add_file "$instance_alias_dir_b" "routingQs_$routing_name_encoded.json" $helper_old
-        cat <<EOD >> $helper_sed
-# Routing Profile: $routing_name
-s%$routing_id_a%$routing_id_b%g
-EOD
-    fi
-done
-test $? -eq 0 || error
-
+restype="RP"
+resource="routing_"
+resfile="routings.json"
+routingQs="routingQs_"
+eval_resources "$restype" "$resource" "$resfile" "$routing_profile_to_ignore" "$routingQs"
 
 ############################################################
 #
@@ -332,48 +489,20 @@ test $? -eq 0 || error
 #
 
 echo Checking Contact Flow Modules ...
-jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/modules.json" |
-tr -d '\r' |
-while read module_id_a module_name; do
-    module_name_encoded=$(path_encode "$module_name")
-    # module_id_b=$(jq -r "select(.Name == \"${module_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/modules.json")
-    module_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/modules.json" | jq -r "select(.Name == \"${module_name//\"/%22}\") | .Id")
-    if [ -z "$module_id_b" ]; then
-        add_file "$instance_alias_dir_a" "module_$module_name_encoded.json" $helper_new
-    else
-        add_file "$instance_alias_dir_b" "module_$module_name_encoded.json" $helper_old
-        cat <<EOD >> $helper_sed
-# Contact Flow Module: $module_name
-s%$module_id_a%$module_id_b%g
-EOD
-    fi
-done
-test $? -eq 0 || error
-
+restype="FlowModule"
+resource="module_"
+resfile="modules.json"
+eval_resources "$restype" "$resource" "$resfile" "none" "none"
 
 ############################################################
 #
 # Contact Flows
 #
-
 echo Checking Contact Flows ...
-jq -r ".Id + \" \" + .Name" "$instance_alias_dir_a/flows.json" |
-tr -d '\r' |
-while read flow_id_a flow_name; do
-    # flow_id_b=$(jq -r "select(.Name == \"${flow_name//\"/\\\"}\") | .Id" "$instance_alias_dir_b/flows.json")
-    flow_id_b=$(sed -e's/\\"/%22/g' "$instance_alias_dir_b/flows.json" | jq -r "select(.Name == \"${flow_name//\"/%22}\") | .Id")
-    flow_name_encoded=$(path_encode "$flow_name")
-    if [ -z "$flow_id_b" ]; then
-        add_file "$instance_alias_dir_a" "flow_$flow_name_encoded.json" $helper_new
-    else
-        add_file "$instance_alias_dir_b" "flow_$flow_name_encoded.json" $helper_old
-        cat <<EOD >> $helper_sed
-# Contact Flow: $flow_name
-s%$flow_id_a%$flow_id_b%g
-EOD
-    fi
-done
-test $? -eq 0 || error
+restype="CF"
+resource="flow_"
+resfile="flows.json"
+eval_resources "$restype" "$resource" "$resfile" "none" "none"
 
 cat > $flow_template <<EOD
 {
@@ -405,6 +534,20 @@ cat > $flow_template <<EOD
 }
 EOD
 
+
+############################################################
+#
+# Quick Connects
+#
+
+echo Checking Quick Connects ...
+restype="QuickConnects"
+resource="quickconnect_"
+resfile="quickconnects.json"
+eval_resources "$restype" "$resource" "$resfile" "none" "none"
+
+
+########################################
 cat <<EOD
 
 These helper files are created:
diff --git a/bin/connect_save b/bin/connect_save
--- a/bin/connect_save
+++ b/bin/connect_save
@@ -4,9 +4,19 @@
 #
 # Get a list of components of an Amazon Connect instance
 #
-
-VERSION=1.1
+# Added support to pass multiple Contact Flow names using pipe delimiter
+#	e.g. ac_save -s instance-1 profile1 "flow-1|flow-2|flow-3"
+#
+# Added support to associate Lex bot to destination connect instance
+# 
+# Added support to migrate Quick Connects
+#
+############################################################
+VERSION=1.2.2b
 SCRIPT_VERSION="$(basename $0) $VERSION"
+
+# Usage: connect_save [-?fseCv] [-p aws_profile] [-c contact_flow_prefix] [-G ignore_prefix] instance_alias
+#     -C                      Produce compact contact flow/module JSON files (useful if those files exceed the API size limit)
 
 USAGE=$(cat <<EOD
 Usage: connect_save [-?fsev] [-p aws_profile] [-c contact_flow_prefix] [-G ignore_prefix] instance_alias
@@ -25,6 +35,7 @@ EOD
 )
 usage() { echo -e "$USAGE" >&2; exit 2; }
 version() { echo -e "$SCRIPT_VERSION"; exit; }
+dos2unix() { tr -d '\r'; }
 
 error() {
     if [ "$#" -ne 0 ]; then
@@ -61,7 +72,17 @@ EOD
     exit 1
 }
 
-hex_code() { printf '%s' "$1" | xxd -u -p -c1 | while read x; do printf "%%%s" "$x"; done }
+hex_cmd=
+if [ -x "$(command -v xxd)" ]; then
+  hex_cmd="xxd -u -p -c1"
+elif [ -x "$(command -v hexdump)" ]; then
+  hex_cmd="hexdump -v -e '/1 \"%02X\n\"'"
+elif [ -x "$(command -v od)" ]; then
+  hex_cmd="od -An -vtx1 | tr [:lower:] [:upper:] | for i in \$(cat); do echo \$i; done"
+fi
+test -z "$hex_cmd" && error "Cannot find any hex conversion commands. Please install one of these: xxd, hexdump, od"
+hex_code() { printf '%s' "$1" | eval "$hex_cmd" | while read x; do printf "%%%s" "$x"; done }
+# hex_code() { printf '%s' "$1" | xxd -u -p -c1 | while read x; do printf "%%%s" "$x"; done }
 
 path_encode()  {
     old_lc_collate=$LC_COLLATE
@@ -77,6 +98,8 @@ path_encode()  {
     LC_COLLATE=$old_lc_collate
 }
 
+# AWS CLI needs to output JSON
+export AWS_DEFAULT_OUTPUT=json
 aws_connect() {
     local cmd=""
     local ii
@@ -107,11 +130,14 @@ ignore_improper_extended_ascii=
 ignore_prefix=
 jq_prefix_filter=
 jq_prefix_filter_text=
+# jq_compact_flag=
+# while getopts "?fseCvp:c:G:" arg; do
 while getopts "?fsevp:c:G:" arg; do
     case "$arg" in
     f)  forced=on;;
     s)  skip_cf_errors=on;;
     e)  ignore_improper_extended_ascii=on;;
+    # C)  jq_compact_flag=" -c";;
     v)  version;;
     p)  profile=$OPTARG;;
     c)  contact_flow_prefix=$OPTARG;;
@@ -195,7 +221,9 @@ aws_connect list-instances --max-items $maxitems > $TEMPFILE || error $LINENO
 instance_id=$(cat $TEMPFILE |
 jq -r ".InstanceSummaryList[] | select(.InstanceAlias == \"$instance_alias\")" |
 tee "$instance_alias_dir/instance.json" |
-jq -r ".Id")
+jq -r ".Id" |
+dos2unix)
+
 echo "Instance ID: $instance_id"
 
 test -n "$instance_id" || error "Instance $instance_alias does not exist"
@@ -241,6 +269,7 @@ tee "$instance_alias_dir/hours.json" |
 echo -e "\n$(jq -s "length") hours of operations listed in \"$instance_alias_dir/hours.json\"$jq_prefix_filter_text"
 
 jq -r ".Id + \" \" + .Name" "$instance_alias_dir/hours.json" |
+dos2unix |
 while read hour_id hour_name; do
     echo "Exporting hours of operation $hour_name"
     hour_name_encoded=$(path_encode "$hour_name")
@@ -269,6 +298,7 @@ tee "$instance_alias_dir/queues.json" |
 echo -e "\n$(jq -s "length") queues listed in \"$instance_alias_dir/queues.json\"$jq_prefix_filter_text"
 
 jq -r ".Id + \" \" + .Name" "$instance_alias_dir/queues.json" |
+dos2unix |
 while read queue_id queue_name; do
     echo "Exporting queue $queue_name"
     queue_name_encoded=$(path_encode "$queue_name")
@@ -276,6 +306,12 @@ while read queue_id queue_name; do
         --instance-id $instance_id \
         --queue-id $queue_id \
         > "$instance_alias_dir/queue_$queue_name_encoded.json" || error $LINENO
+	
+	## List quick connects associated with the queue
+    aws_connect list-queue-quick-connects \
+        --instance-id $instance_id \
+        --queue-id $queue_id \
+        > "$instance_alias_dir/queue_qc_$queue_name_encoded.json" || error $LINENO
 done
 test $? -eq 0 || error
 
@@ -297,6 +333,7 @@ tee "$instance_alias_dir/routings.json" |
 echo -e "\n$(jq -s "length") routing profiles listed in \"$instance_alias_dir/routings.json\"$jq_prefix_filter_text"
 
 jq -r ".Id + \" \" + .Name" "$instance_alias_dir/routings.json" |
+dos2unix |
 while read routing_id routing_name; do
     echo "Exporting routing profile $routing_name"
     routing_name_encoded=$(path_encode "$routing_name")
@@ -337,6 +374,7 @@ echo -e "\n$(jq -s "length") contact flow modules listed in \"$instance_alias_di
 
 cat "$instance_alias_dir/modules.json" > $TEMPFILE
 jq -r ".Id + \" \" + .Name" $TEMPFILE |
+dos2unix |
 while read module_id module_name; do
     echo "Exporting contact flow module $module_name"
     module_name_encoded=$(path_encode "$module_name")
@@ -347,7 +385,7 @@ while read module_id module_name; do
     if [ -s $TEMPCF ]; then
         # Status == "saved" is considered a failure,
         # not to copy an unpublished contact flow module
-        cf_status=$(jq -r ".ContactFlowModule.Status" $TEMPCF)
+        cf_status=$(jq -r ".ContactFlowModule.Status" $TEMPCF | dos2unix)
         if [ "$cf_status" != "published" ]; then
             echo
             echo "$module_name: Contact flow module not published"
@@ -357,7 +395,9 @@ while read module_id module_name; do
         if [ -s $TEMPCF ]; then
             cat $TEMPCF |
             jq -r '.ContactFlowModule.Content' > "$instance_alias_dir/module_$module_name_encoded.json"
-            # fix_module_json "$instance_alias_dir/module_$module_name_encoded.json"
+	    cat $TEMPCF |
+            jq -r '.ContactFlowModule.Description' > "$instance_alias_dir/moduledesc_$module_name_encoded"
+            # fix_module_json "$instance_alias_dir/module_$module_name.json"
         fi
     fi
 done
@@ -388,19 +428,71 @@ echo -e "\n$(jq -s "length") contact flows listed in \"$instance_alias_dir/flows
 
 cat "$instance_alias_dir/flows.json" > $TEMPFILE
 jq -r ".Id + \" \" + .Name" $TEMPFILE |
+dos2unix |
 while read flow_id flow_name; do
     echo "Exporting contact flow $flow_name"
+    flow_name_encoded=$(path_encode "$flow_name")
     aws_connect describe-contact-flow \
         --instance-id $instance_id \
         --contact-flow-id $flow_id > $TEMPCF \
         || error $LINENO "$flow_name" "$instance_alias_dir/flows.json"
-    flow_name_encoded=$(path_encode "$flow_name")
     if [ -s $TEMPCF ]; then
         cat $TEMPCF |
         jq -r '.ContactFlow.Content' > "$instance_alias_dir/flow_$flow_name_encoded.json"
+        cat $TEMPCF |
+        jq -r '.ContactFlow.Description' > "$instance_alias_dir/flowdesc_$flow_name_encoded"
+
     fi
 done
 test $? -eq 0 || error
 
+############################################################
+#
+# Quick Connects
+#
+aws_connect list-quick-connects \
+	--instance-id $instance_id \
+	--max-items $maxitems \
+	> $TEMPFILE || error $LINENO
+
+cat $TEMPFILE |
+	jq -r ".QuickConnectSummaryList[]$jq_prefix_filter" |
+	jq -s "sort_by(.Name) | .[]" |
+	tee "$instance_alias_dir/quickconnects.json" |
+
+echo -e "\n$(jq -s "length") quick connects listed in \"$instance_alias_dir/quickconnects.json\"$jq_prefix_filter_text"
+
+jq -r ".Id + \" \" + .Name" "$instance_alias_dir/quickconnects.json" |
+dos2unix |
+while read qc_id qc_name; do
+    echo "Exporting quick connect $qc_name"
+    qc_name_encoded=$(path_encode "$qc_name")
+    aws_connect describe-quick-connect \
+	    --instance-id $instance_id \
+	    --quick-connect-id $qc_id \
+	    > "$instance_alias_dir/quickconnect_$qc_name_encoded.json" || error $LINENO
+done
+test $? -eq 0 || error
+
+
+############################################################
+#
+# Phone numbers
+#
+aws_connect list-phone-numbers \
+	--instance-id $instance_id \
+	--max-items $maxitems \
+	> $TEMPFILE || error $LINENO
+
+cat $TEMPFILE |
+	jq -r ".PhoneNumberSummaryList[]$jq_prefix_filter" |
+	tee "$instance_alias_dir/phonenumbers.json" |
+
+echo -e "\n$(jq -s "length") phone numbers listed in \"$instance_alias_dir/phonenumbers.json\"$jq_prefix_filter_text"
+
+test $? -eq 0 || error
+
+
+############################################################
 echo
 echo "All done"
