Make error messages consistent

diff --git a/bin/connect_diff b/bin/connect_diff
--- a/bin/connect_diff
+++ b/bin/connect_diff
@@ -26,14 +26,14 @@ EOD
 )
 usage() { echo -e "$USAGE" >&2; exit 2; }
 
-error() { echo "$*" >&2; exit 1; }
+error() { echo -e "Error: $1" >&2; exit 1; }
 
 add_file() {
     alias_dir="$1"
     file_suffix="$2"
     helper_file="$3"
     if [ ! -s "$alias_dir/$file_suffix" ]; then
-        error "Error: File missing or empty: $alias_dir/$file_suffix"
+        error "File missing or empty: $alias_dir/$file_suffix"
         exit 1
     else
         echo "$file_suffix" >> $helper_file
@@ -72,7 +72,6 @@ if [ -d $helper ]; then
 fi
 
 routing_profile_to_ignore="Basic Routing Profile"
-# module_template=$helper/module_template.json
 flow_template=$helper/flow_template.json
 
 cat <<EOD
@@ -90,8 +89,8 @@ if [ ! -d "$instance_alias_dir_b" ]; then
     errorMsg="$errorMsg $instance_alias_dir_b"
 fi
 if [ -n "$errorMsg" ]; then
-    errorMsg="Error: Cannot find instance directories:$errorMsg"
-    error $errorMsg
+    errorMsg="Cannot find instance directories:$errorMsg"
+    error "$errorMsg"
 fi
 
 mkdir -p $helper
@@ -275,52 +274,6 @@ EOD
 done
 test $? -eq 0 || error
 
-# cat > $module_template <<EOD
-# {
-#     "Version": "2019-10-30",
-#     "StartAction": "a47b05b9-2a3f-4bb7-b724-c967ba056e6a",
-#     "Metadata": {
-#         "entryPointPosition": {
-#             "x": 20,
-#             "y": 20
-#         },
-#         "snapToGrid": false,
-#         "ActionMetadata": {
-#             "a47b05b9-2a3f-4bb7-b724-c967ba056e6a": {
-#                 "position": {
-#                     "x": 161,
-#                     "y": 22
-#                 }
-#             }
-#         }
-#     },
-#     "Actions": [
-#         {
-#             "Identifier": "a47b05b9-2a3f-4bb7-b724-c967ba056e6a",
-#             "Type": "EndFlowModuleExecution",
-#             "Parameters": {},
-#             "Transitions": {}
-#         }
-#     ],
-#     "Settings": {
-#         "InputParameters": [],
-#         "OutputParameters": [],
-#         "Transitions": [
-#             {
-#                 "DisplayName": "Success",
-#                 "ReferenceName": "Success",
-#                 "Description": ""
-#             },
-#             {
-#                 "DisplayName": "Error",
-#                 "ReferenceName": "Error",
-#                 "Description": ""
-#             }
-#         ]
-#     }
-# }
-# EOD
-
 
 ############################################################
 #
@@ -377,7 +330,6 @@ echo "$helper_var: About the source and target Amazon Connect instances"
 echo "$helper_new: Components to add to $instance_alias_dir_b"
 echo "$helper_old: Components to update for $instance_alias_dir_b based on $instance_alias_dir_a"
 echo "$helper_sed: SED script used to update components"
-# echo "$module_template: Contact Flow Module template json"
 echo "$flow_template: Contact Flow template json"
 echo
 echo "All done"
diff --git a/bin/connect_save b/bin/connect_save
--- a/bin/connect_save
+++ b/bin/connect_save
@@ -19,7 +19,7 @@ EOD
 )
 usage() { echo -e "$USAGE" >&2; exit 2; }
 
-error() { echo "$1" >&2; exit 1; }
+error() { echo -e "Error: $1" >&2; exit 1; }
 
 fix_module_json() {
     # A workaround for AWS CLI failed to create contact flow modules
@@ -47,6 +47,8 @@ TEMPFILE=$(mktemp)
 TEMPFILE2=${TEMPFILE}_2
 trap 'rm -r -- $TEMPFILE $TEMPFILE2' EXIT
 touch $TEMPFILE $TEMPFILE2
+
+warning_awscli="Please install the latest AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
 
 forced=
 jq_prefix_filter=
@@ -94,7 +96,7 @@ EOD
 
 # First aws cli; only mkdir if successful.
 aws connect list-instances $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 mkdir -p $instance_alias_dir
 
 instance_id=$(cat $TEMPFILE |
@@ -120,7 +122,7 @@ echo "instance_contact_flow_prefix=\"$contact_flow_prefix\"" >> $instance_alias_
 aws connect list-prompts \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".PromptSummaryList |= sort_by(.Name) | .[][]" |
 tee $instance_alias_dir/prompts.json |
@@ -135,7 +137,7 @@ echo -e "\n$(jq -s "length") prompts listed in $instance_alias_dir/prompts.json"
 aws connect list-hours-of-operations \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".HoursOfOperationSummaryList |= sort_by(.Name) | .[][]" |
 tee $instance_alias_dir/hours.json |
@@ -148,7 +150,7 @@ while read hour_id hour_name; do
         --instance-id $instance_id \
         --hours-of-operation-id $hour_id \
         $profile_flag > "$instance_alias_dir/hour_$hour_name.json"
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 done
 test $? -eq 0 || error
 
@@ -161,7 +163,7 @@ test $? -eq 0 || error
 aws connect list-queues \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".QueueSummaryList[] | select(.QueueType != \"AGENT\")$jq_prefix_filter" |
 jq -s "sort_by(.Name) | .[]" |
@@ -175,7 +177,7 @@ while read queue_id queue_name; do
         --instance-id $instance_id \
         --queue-id $queue_id \
         $profile_flag > "$instance_alias_dir/queue_$queue_name.json"
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 done
 test $? -eq 0 || error
 
@@ -188,7 +190,7 @@ test $? -eq 0 || error
 aws connect list-routing-profiles \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".RoutingProfileSummaryList[]$jq_prefix_filter" |
 jq -s "sort_by(.Name) | .[]" |
@@ -202,12 +204,12 @@ while read routing_id routing_name; do
         --instance-id $instance_id \
         --routing-profile-id $routing_id \
         $profile_flag > "$instance_alias_dir/routing_$routing_name.json"
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
     aws connect list-routing-profile-queues \
         --instance-id $instance_id \
         --routing-profile-id $routing_id \
         $profile_flag > "$instance_alias_dir/routingQs_$routing_name.json"
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 done
 test $? -eq 0 || error
 
@@ -220,7 +222,7 @@ test $? -eq 0 || error
 aws connect list-contact-flow-modules \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".ContactFlowModulesSummaryList[]${contact_flow_prefix_filter}${jq_prefix_filter}" |
 jq -s "sort_by(.Name) | .[]" |
@@ -239,7 +241,7 @@ while read module_id module_name; do
     aws connect describe-contact-flow-module \
         --instance-id $instance_id \
         --contact-flow-module-id $module_id $profile_flag > $TEMPFILE
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
     cat $TEMPFILE |
     jq -r '.ContactFlowModule.Content' > "$instance_alias_dir/module_$module_name.json"
     fix_module_json "$instance_alias_dir/module_$module_name.json"
@@ -255,7 +257,7 @@ test $? -eq 0 || error
 aws connect list-contact-flows \
     --instance-id $instance_id \
     $profile_flag > $TEMPFILE
-test $? -eq 0 || error
+test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
 cat $TEMPFILE |
 jq -r ".ContactFlowSummaryList[]${contact_flow_prefix_filter}${jq_prefix_filter}" |
 jq -s "sort_by(.Name) | .[]" |
@@ -274,7 +276,7 @@ while read flow_id flow_name; do
     aws connect describe-contact-flow \
         --instance-id $instance_id \
         --contact-flow-id $flow_id $profile_flag > $TEMPFILE
-    test $? -eq 0 || error
+    test $? -eq 0 || error "AWS CLI error at line $LINENO.\n$warning_awscli"
     cat $TEMPFILE |
     jq -r '.ContactFlow.Content' > "$instance_alias_dir/flow_$flow_name.json"
 done
